name: Android Fastlane With Firebase App Distribution Workflow

on:
  push:
    branches:
      - master
jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout my repo code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: "17"
      - name: Verify Java version
        run: java -version
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build Android artifact (appbundle with flavor fallback)
        run: |
          set -e
          flutter --version
          flutter pub get
          mkdir -p build
          # Try production flavor first (most likely release)
          set +e
          flutter build appbundle --flavor production --release -v 2>&1 | tee build/flutter_build_production.log
          PROD_STATUS=$?
          if [ $PROD_STATUS -ne 0 ]; then
            echo "Production flavor build failed (see build/flutter_build_production.log). Trying development flavor..."
            flutter build appbundle --flavor development --release -v 2>&1 | tee build/flutter_build_development.log
          fi
          set -e
          echo "Build outputs (top-level):"
          ls -R build || true
        working-directory: .

      - name: Upload build outputs and logs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-build-outputs
          path: |
            build/**
            android/app/build/outputs/**

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
          working-directory: android

      - name: Install gem dependencies (bundle install)
        run: |
          bundle config set path 'vendor/bundle'
          bundle install --jobs 4 --retry 3
        working-directory: android

      - name: Build and Distribute App
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }} # أو FIREBASE_SA_JSON
          SKIP_BUILD: "true"
        run: |
          bundle exec fastlane android firebase_distribution
        working-directory: android
