name: Android Fastlane With Firebase App Distribution Workflow

on:
  push:
    # run on pushes to any branch; restrict if you want specific branches only
    branches:
      - master
jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout my repo code
        # use the official checkout action tag for clarity and maintainability
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: "11"
      - name: Install Flutter
        # use the released v2 tag for maintainability; supports 'channel' input
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.7"
          bundler-cache: true
          working-directory: android

      - name: Build and Distribute App
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }} # أو FIREBASE_SA_JSON
        run: |
          bundle exec fastlane android firebase_distribution
        working-directory: android
