name: android-ci-firebase-dist

on:
  push:
    # run on pushes to any branch; restrict if you want specific branches only
    branches: [master]
jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout my repo code
        # use the official checkout action tag for clarity and maintainability
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Flutter
        # use the released v2 tag for maintainability; supports 'channel' input
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Accept Android SDK licenses
        # try to accept licenses via sdkmanager in PATH, else try common SDK locations
        run: |
          if command -v sdkmanager >/dev/null 2>&1; then
            yes | sdkmanager --licenses
          elif [ -x "${ANDROID_SDK_ROOT:-$ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager" ]; then
            yes | "${ANDROID_SDK_ROOT:-$ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager" --licenses
          elif [ -x "${ANDROID_SDK_ROOT:-$ANDROID_HOME}/tools/bin/sdkmanager" ]; then
            yes | "${ANDROID_SDK_ROOT:-$ANDROID_HOME}/tools/bin/sdkmanager" --licenses
          else
            echo "sdkmanager not found; skipping license acceptance"
          fi

      - name: Setup Node.js (for Firebase CLI)
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.7"
          bundler-cache: true
          working-directory: android

      - name: Build & Distribute with Fastlane
        working-directory: android
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }} # أو FIREBASE_SA_JSON
        run: bundle exec fastlane android firebase_distribution
