name: android-ci-firebase-dist

on:
  push:
    # run on pushes to any branch; restrict if you want specific branches only
    branches: ["**"]
  pull_request:
    # run on PR open/update/reopen so CI runs for PRs
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # use the official checkout action tag for clarity and maintainability
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Flutter
        uses: subosito/flutter-action@a2d5009f2784a9c51e91d069bf5e4e01e1dfe0e1
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Setup Ruby (CI-safe)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
          working-directory: android

      # احذف هذه الخطوة إذا ستستخدم Service Account JSON
      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Build & Distribute with Fastlane
        working-directory: android
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }} # أو FIREBASE_SA_JSON
        run: bundle exec fastlane android firebase_distribution
